apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: kmerrell
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: feature-toggle
        - secretRef:
            name: db-secret
        name: app-deployment
        image: harbor.dev.afsmtddso.com/kmerrell-harbor-project/app@sha256:da2ca7fe4569ceb48f1f203b75bc136e65c69d69981e490f7e817a3c5dbe1e20
        ports:
        - containerPort: 5000
