apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: kmerrell
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: app-deployment
        image: docker pull harbor.dev.afsmtddso.com/kmerrell-harbor-project/app:c22cb22-7c71f88
        ports:
        - containerPort: 5000
